# Generated by Django 5.1 on 2024-08-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sponsores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('classes', models.EmailField(max_length=100)),
                ('packages', models.EmailField(max_length=100)),
                ('tutorials', models.EmailField(max_length=100)),
            ],
        ),
    ]
