# Generated by Django 5.1 on 2024-08-25 09:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_plan_prices_plan_price_alter_plan_classes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Program adı')),
                ('explanation', ckeditor.fields.RichTextField(max_length=100, verbose_name='Proqram açıqlaması')),
                ('icon', models.FileField(upload_to='', verbose_name='Program ikonu')),
                ('video', models.FileField(upload_to='Program_videos/')),
                ('question1', models.CharField(max_length=100, verbose_name='Sual1')),
                ('answer1', ckeditor.fields.RichTextField(max_length=300, verbose_name='Cavab1')),
                ('question2', models.CharField(max_length=100, verbose_name='Sual2')),
                ('answer2', ckeditor.fields.RichTextField(max_length=300, verbose_name='Cavab2')),
                ('question3', models.CharField(max_length=100, verbose_name='Sual3')),
                ('answer3', ckeditor.fields.RichTextField(max_length=300, verbose_name='Cavab3')),
                ('duration', models.CharField(max_length=100, verbose_name='Müddət')),
                ('intensity', models.CharField(max_length=100, verbose_name='İntensivlik')),
                ('level', models.CharField(max_length=100, verbose_name='Səviyyəsiz')),
                ('schedule', models.CharField(max_length=100, verbose_name='Planlama')),
            ],
        ),
    ]
