# Generated by Django 5.1 on 2024-08-25 10:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='answer1',
            field=ckeditor.fields.RichTextField(max_length=500, verbose_name='Cavab1'),
        ),
        migrations.AlterField(
            model_name='program',
            name='answer2',
            field=ckeditor.fields.RichTextField(max_length=500, verbose_name='Cavab2'),
        ),
        migrations.AlterField(
            model_name='program',
            name='answer3',
            field=ckeditor.fields.RichTextField(max_length=500, verbose_name='Cavab3'),
        ),
    ]
