# Generated by Django 5.1 on 2024-08-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_profile_plans_remove_profile_programs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='program',
            new_name='programs',
        ),
    ]
