# Generated by Django 5.1 on 2024-08-26 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_profile_programs_profile_programs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='programs',
        ),
        migrations.AddField(
            model_name='profile',
            name='programs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.program'),
        ),
    ]
