# Generated by Django 5.1 on 2024-08-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_profile_programs_profile_programs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='programs',
            new_name='program',
        ),
    ]
