# Generated by Django 5.1 on 2024-08-26 17:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_programs_profile_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='about',
            field=ckeditor.fields.RichTextField(default='', max_length=800, verbose_name='Haqqında'),
        ),
        migrations.AddField(
            model_name='plan',
            name='istheright',
            field=ckeditor.fields.RichTextField(default='', max_length=800, verbose_name='Niye bu plan?'),
        ),
    ]
