# Generated by Django 5.1 on 2024-08-28 03:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('address', models.CharField(max_length=100, verbose_name='Ünvan')),
            ],
        ),
        migrations.CreateModel(
            name='Incoming_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Tam adı')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('input_title', models.CharField(max_length=100, verbose_name='Başlıq')),
                ('input_message', ckeditor.fields.RichTextField(max_length=500, verbose_name='Mesaj')),
            ],
        ),
    ]
