# Generated by Django 5.1 on 2024-08-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_faqquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqquestion',
            name='normalized_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
