# Generated by Django 5.1 on 2024-09-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_social_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Planın müddəti (gün)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='remaining_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Kalan Gün Sayısı'),
        ),
    ]
