# Generated by Django 5.1 on 2024-09-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_plan_duration_days_profile_remaining_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='postal',
            field=models.CharField(default='', max_length=10),
        ),
    ]
