# Generated by Django 5.1 on 2024-09-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_newslettermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettermessage',
            name='ishappy',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
