# Generated by Django 5.1 on 2024-09-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_newslettermessage_ishappy_delete_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslettermessage',
            old_name='name',
            new_name='username',
        ),
    ]
