# Generated by Django 5.1 on 2024-09-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_rename_name_newslettermessage_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettermessage',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newslettermessage',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
