# Generated by Django 5.1 on 2024-08-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_user_image_passwordresetcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
