# Generated by Django 5.1 on 2024-08-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_plans_plan_rename_sponsores_sponsore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='prices',
        ),
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Plan dəyəri'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='classes',
            field=models.CharField(max_length=100, verbose_name='Daxil olan sinif sayı'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Plan adı'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='packages',
            field=models.CharField(max_length=100, verbose_name='Daxil olanlar'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tutorials',
            field=models.CharField(max_length=100, verbose_name='Qaynaqlar'),
        ),
        migrations.AlterField(
            model_name='sponsore',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sponsore',
            name='icon',
            field=models.ImageField(upload_to='', verbose_name='Sponsor ikonu'),
        ),
        migrations.AlterField(
            model_name='sponsore',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Sponsor adı'),
        ),
    ]
