# Generated by Django 5.1 on 2024-08-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ishappy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='plans',
            field=models.ManyToManyField(blank=True, to='core.plan'),
        ),
        migrations.AddField(
            model_name='profile',
            name='programs',
            field=models.ManyToManyField(blank=True, to='core.program'),
        ),
    ]
