# Generated by Django 5.1 on 2024-08-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profile_plan_profile_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='plans',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='programs',
        ),
    ]
