# Generated by Django 5.1 on 2024-08-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_programs_profile_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='program',
            new_name='programs',
        ),
    ]
