# Generated by Django 5.1 on 2024-08-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_program_profile_programs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='programs',
        ),
        migrations.AddField(
            model_name='profile',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='core.program'),
        ),
    ]
