# Generated by Django 5.1 on 2024-08-26 17:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_plan_about_plan_istheright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='about',
            field=ckeditor.fields.RichTextField(default='', max_length=1000, verbose_name='Haqqında'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='istheright',
            field=ckeditor.fields.RichTextField(default='', max_length=1000, verbose_name='Niye bu plan?'),
        ),
    ]
