# Generated by Django 5.1 on 2024-08-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_plan_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('surname', models.CharField(max_length=100, verbose_name='Soyadı')),
                ('photo', models.FileField(upload_to='')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('classes', models.CharField(max_length=100, verbose_name='Vəzifəsi')),
                ('facebook', models.CharField(max_length=100, verbose_name='Facebook')),
                ('linkedin', models.CharField(max_length=100, verbose_name='Linkedin')),
                ('twitter', models.CharField(max_length=100, verbose_name='twitter')),
            ],
        ),
    ]
