# Generated by Django 5.1 on 2024-08-28 13:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_contactmessage_delete_incoming_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlıq')),
                ('contents', ckeditor.fields.RichTextField(max_length=100, verbose_name='Proqram açıqlaması')),
                ('media', models.ImageField(upload_to='blog', verbose_name='Media')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('classes', models.CharField(max_length=100, verbose_name='Mövzu')),
            ],
        ),
    ]
