# Generated by Django 5.1 on 2024-08-29 06:39

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_blog_classes_remove_trainer_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.trainer'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(default='', max_length=100, verbose_name='Mövzu'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='contents',
            field=ckeditor.fields.RichTextField(max_length=1800, verbose_name='Proqram açıqlaması'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='position',
            field=models.CharField(default='', max_length=100, verbose_name='Vəzifəsi'),
        ),
    ]
