# Generated by Django 5.1 on 2024-09-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_wishlist_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(default='credit_card', max_length=100, verbose_name='Ödə'),
        ),
    ]
