# Generated by Django 5.1 on 2024-09-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='social',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='social',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='social',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='social',
            name='youtube',
        ),
        migrations.AddField(
            model_name='social',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Adresi'),
        ),
        migrations.AddField(
            model_name='social',
            name='icon',
            field=models.CharField(default='', max_length=50, verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='social',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Adi'),
        ),
    ]
