# Generated by Django 5.1 on 2024-09-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_social_facebook_remove_social_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.FileField(upload_to=''),
        ),
    ]
